-- Insert a new test property request to verify Telegram notifications
INSERT INTO public.property_requests (
  user_id,
  title,
  description,
  price,
  location,
  latitude,
  longitude,
  bedrooms,
  bathrooms,
  area,
  emirate,
  type,
  property_type,
  contact_name,
  contact_email,
  contact_phone,
  submitter_type,
  status,
  amenities,
  user_message
) VALUES (
  'b8f20b8b-d80d-4ff6-a19f-46ea6c9da714', -- Admin user ID
  'Luxury Villa - Bot Test #2',
  'This is a second test property listing to verify Telegram bot is responding correctly with /start command. Beautiful 3-bedroom villa with private pool and garden.',
  2800000,
  'Palm Jumeirah, Dubai',
  25.1124,
  55.1390,
  3,
  4,
  2500.0,
  'Dubai',
  'sale',
  'Villa',
  'Test Admin',
  'admin@homeapp.ae',
  '+971 50 999 8888',
  'broker',
  'pending',
  '["Private Pool", "Garden", "Maid Room", "Beach Access", "Smart Home"]'::jsonb,
  'Second test submission - checking if Telegram webhook is configured and bot responds to /start'
);