-- Insert a test property request to verify Telegram notifications
INSERT INTO public.property_requests (
  user_id,
  title,
  description,
  price,
  location,
  latitude,
  longitude,
  bedrooms,
  bathrooms,
  area,
  emirate,
  type,
  property_type,
  contact_name,
  contact_email,
  contact_phone,
  submitter_type,
  status,
  amenities,
  user_message
) VALUES (
  'b8f20b8b-d80d-4ff6-a19f-46ea6c9da714',
  'Luxury Villa - No Link Test',
  'Testing Telegram notification without admin panel link. Stunning beachfront villa with private pool and garden.',
  8500000,
  'Palm Jumeirah',
  25.1124,
  55.1390,
  5,
  6,
  5500.0,
  'Dubai',
  'sale',
  'Villa',
  'Link Test User',
  'linktest@homeapp.ae',
  '+971 50 888 9999',
  'owner',
  'pending',
  '["Private Pool", "Beach Access", "Garden", "Maid Room", "Private Parking"]'::jsonb,
  'Testing notification format without admin panel link in Telegram'
);