-- Insert another test property request to verify Telegram channel notifications
INSERT INTO public.property_requests (
  user_id,
  title,
  description,
  price,
  location,
  latitude,
  longitude,
  bedrooms,
  bathrooms,
  area,
  emirate,
  type,
  property_type,
  contact_name,
  contact_email,
  contact_phone,
  submitter_type,
  status,
  amenities,
  user_message
) VALUES (
  'b8f20b8b-d80d-4ff6-a19f-46ea6c9da714',
  'Modern Penthouse - Channel Test',
  'Testing Telegram channel notifications. Stunning penthouse with panoramic city views, private terrace, and infinity pool.',
  4500000,
  'Downtown Dubai',
  25.1972,
  55.2744,
  4,
  5,
  3800.0,
  'Dubai',
  'sale',
  'Penthouse',
  'Channel Test',
  'test@homeapp.ae',
  '+971 50 777 6666',
  'owner',
  'pending',
  '["Infinity Pool", "Private Terrace", "Panoramic Views", "Home Cinema", "Wine Cellar"]'::jsonb,
  'Testing notification to Telegram channel with ID: -1003176895529'
);