// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwrzpawuvdqjintyhzkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3cnpwYXd1dmRxamludHloemttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjkzMDYsImV4cCI6MjA2NTg0NTMwNn0.GnC-m7ke8NG6V_t8CgzHJbhq44lSK_XCXcNnbAs7Ha8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);